applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'persona_app'


urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='Pagina_Inicio'
    ),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleado.as_view(),
        name='empleados_all'
    ),
    path(
        'listar-empleado-admin/',
        views.ListAllEmpleadoAdmin.as_view(),
        name='empleados_all_admin'
    ),
    path(
        'lista-by-area/<shortname>',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'buscar-empleado/',
        views.ListEmpleadosByKword.as_view()
    ),
    path(
        'listar-habilidades-empleado/',
        views.ListHabilidadesEmpleado.as_view()
    ),
    path(
        'ver-empleado/<pk>',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'ver-empleado-trabajo/',
        views.ListByTrabajoEmpleado.as_view()
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='actualizar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluiomos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
#
from applications.departamento.models import Departamento

from ckeditor.fields import RichTextField


class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleados'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad

# Create your models here.


class Empleado(models.Model):
    """Modelo para tabla empleado"""

    JOB_CHOICES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('3', 'Economista'),
        ('4', 'Otro')
    )
    # Contador
    # Administrador
    # Economista
    # Otro
    first_name = models.CharField(
        'Nombres',
        max_length=50)
    last_name = models.CharField(
        'apellidos',
        max_length=50
    )
    full_name = models.CharField(
        'Nombres completos',
        max_length=120,
        blank=True
    )
    job = models.CharField(
        'trabajo',
        max_length=1,
        choices=JOB_CHOICES
    )
    departamento = models.ForeignKey(
        Departamento,
        on_delete=models.CASCADE
    )
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    Habilidades = models.ManyToManyField(
        Habilidades
    )
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Mi Empresa'
        verbose_name_plural = 'Areas de los Empleados'
        ordering = ['first_name']
        unique_together = ('first_name', 'last_name')

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

applications/persona/forms.py
from django import forms

from .models import Empleado


class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'Habilidades',
        )
        widgets = {
            'Habilidades': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
# Create your views here.
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)
#
from .models import Empleado

# forms

from .forms import EmpleadoForm


class ListAllEmpleado(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    ordering = 'first_name'
    model = Empleado
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        # icontains busca registro
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        return lista


class ListAllEmpleadoAdmin(ListView):
    template_name = 'persona/list_empleados.html'
    paginate_by = 10
    ordering = 'first_name'
    model = Empleado
    context_object_name = 'empleados'


class ListByAreaEmpleado(ListView):
    """ Lista de empleados por area"""
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self):

        area = self.kwargs['shortname']
        lista = Empleado.objects.filter(
            departamento__shor_name=area
        )
        return lista


class ListByTrabajoEmpleado(ListView):
    """ Lista de empleados por area"""
    template_name = 'persona/list_by_trabajo.html'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            job=palabra_clave
        )

        return lista


class ListEmpleadosByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):

        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name=palabra_clave
        )

        return lista


class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'Habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=4)

        return empleado.Habilidades.all()

# 1. Listar todos los empleados de la empresa
# 2. Listar todos los empleados que pertenecen a una area de la empresa
# 3. Listar empleados por trabajo
# 4. Listar los empleados por palabra clave
# 5. Listar habilidades de un empleado


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context["titulo"] = 'Empleado del mes'
        return context

# Clases para guardar un registro


class InicioView(TemplateView):
    # pagina de inicio
    template_name = "inicio.html"


class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:empleados_all_admin')

    def form_valid(self, form):
        # LOGICA DEL PROCESO
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = [
        'first_name',
        'last_name',
        'full_name',
        'job',
        'departamento',
        'Habilidades',
        'avatar'
    ]
    success_url = reverse_lazy('persona_app:empleados_all_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        # LOGICA DEL PROCESO
        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:empleados_all_admin')

templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
Registrar Empleado
{% endblock title %}

{% block content %}


{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Crear un nuevo empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %}

            <div class="medium-6 cell">
                <label>Nombres:
                    {{ form.first_name }}
                </label>
            </div>

            <div class="medium-6 cell">
                <label>Apellidos:
                    {{ form.last_name }}
                </label>
            </div>

            <div class="medium-6 cell">
                <label>Trabajo:
                    {{ form.job }}
                </label>
            </div>

            <div class="medium-6 cell">
                <label>Departamento:
                    {{ form.departamento }}
                </label>
            </div>

            <div class="medium-12 cell">
                <label>Habilidades:
                    {{ form.Habilidades }}
                </label>
            </div>

            <div class="medium-12 cell">
                <label>Imagen:
                    {{ form.avatar }}
                </label>
            </div>


            <div class="medium-12 cell">
                <button type="submit" class="success button">Guardar</button>
            </div>

        </form>
    </div>
</div>




{% endblock content %}

templates/persona/by_kword.html
<h1>Buscar Empleados por palabra clave</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese el nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista Resultados</h3>

<u>

    {% for e in object_list %}

    <li>{{e}}</li>

    {% endfor %}

</u>

templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
Eliminar Empleados
{% endblock title %}

{% block content %}


{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h3 class="cell">Alerta</h3>
        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout alert" data-closable>
                <h5>Confirme que desea eliminar al empleado: {{ object.full_name }}?</h5>
                <button type="submit" class="alert button">Confirmar</button>
                <a aria-label="Dismiss alert" href="{% url 'persona_app:empleados_all_admin' %}"
                    class="close-button">x</a>
            </div>
        </form>
    </div>
</div>


{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block title %}

{{object.full_name}}

{% endblock title %}


{% block content %}


{% include 'includes/header.html' %}


<form>
    <div class="grid-container">
        <div class="grid-x grid-padding-x align-center">
            <div class="cell large-4  card" style="width: 300px; margin-top: 10px;">
                <div class="card-divider">
                    <h4> {{ empleado.get_job_display }} </h4>
                </div>

                {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">
                {% else %}
                <img src="{% static 'img/imgnotfound.png' %}">
                {% endif %}

                <div class="card-section">
                    <h4>{{ empleado.full_name }}</h4>
                    <p>{{ empleado.last_name }}</p>
                    <p>{{ empleado.departamento.shor_name }}</p>
                    <p><span class="label">Habilidades</span></p>

                    {% for h in empleado.Habilidades.all %}

                    <li>{{ h.habilidad }}</li>

                    {% endfor %}


                </div>
            </div>
        </div>
    </div>
</form>


{% endblock content %}

templates/persona/habilidades.html
<h1>Habilidades del empleado</h1>

<u>
    <h1>{{ Habilidades.first_name }}</h1>
    {% for e in Habilidades %}

    <li>{{e}}</li>

    {% endfor %}

</u>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}


{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">

        <h1 class="cell">Lista de Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="get"> {% csrf_token %}
            <div class="cell large-7">
                <input type="search" id="kword" name="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>

        <div class="cell">
            <table class="hover">
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTOS</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>

                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">

            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}

                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>

                    {% endif %}


                    {% for pagina in paginator.page_range %}


                    {% ifequal pagina page_obj.number  %}

                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>

                    {% else %}

                    <li><a href="?page={{pagina}}">{{ pagina }}</a></li>

                    {% endifequal %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>

                    {% endif %}
                </ul>
            </nav>
            {% endif %}


        </div>
    </div>
</div>
{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
Lista de empleados por area
{% endblock title %}
Lista de empleados por area

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <div class="cell">
            <div class="cell">
                <table class="hover">
                    <thead>
                        <tr>
                            <th width="200">ID</th>
                            <th>NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTOS</th>
                            <th width="150">ACCION</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for e in empleados %}
                        <tr>
                            <td>{{ e.id }}</td>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento }}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/list_by_trabajo.html
<h1>Lista de Empleados Por Trabajo</h1>
<form method="GET">{% csrf_token %}
    <select name="kword" required="" id="kword">

        <option value="" selected="">---------</option>

        <option value="0">Contador</option>

        <option value="1">Administrador</option>

        <option value="3">Economista</option>

        <option value="4">Otro</option>

    </select>
    <button type="submit">Buscar</button>

</form>

<h3>Lista Resultados</h3>

<u>

    {% for e in object_list %}

    <li>{{e}}</li>

    {% endfor %}

</u>

templates/persona/list_empleados.html
{% extends 'base.html' %}

{% block content %}


{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">

        <h1 class="cell">Lista de Empleados</h1>
        <div class="cell">
            <table class="hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>NOMBRES</th>
                        <th>APELLIDOS</th>
                        <th>DEPARTAMENTOS</th>
                        <th>ACCION</th>
                    </tr>
                </thead>
                <tbody>

                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:actualizar_empleado' e.id %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">

            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}

                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>

                    {% endif %}


                    {% for pagina in paginator.page_range %}


                    {% ifequal pagina page_obj.number  %}

                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>

                    {% else %}

                    <li><a href="?page={{pagina}}">{{ pagina }}</a></li>

                    {% endifequal %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>

                    {% endif %}
                </ul>
            </nav>
            {% endif %}


        </div>
    </div>
</div>
{% endblock content %}

templates/persona/success.html
<h3>Se guardo correctamente el empleado</h3>

templates/persona/update.html
{% extends 'base.html' %}


{% block title %}
Editar Empleado
{% endblock title %}

{% block content %}


{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Modificar Registros De Empleado</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST"> {% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                    {{ form.first_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{ form.last_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Nombre Completo
                    {{ form.full_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                    {{ form.job }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{ form.departamento }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Habilidades:
                    {{ form.Habilidades }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Imagen:
                    {{ form.avatar }}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="success button">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}