applications/departamento/urls.py
from django.contrib import admin
from django.urls import path


from . import views

app_name = 'departamento_app'

urlpatterns = [
    path(
        'departamento-lista/',
        views.DepartamentoListView.as_view(),
        name='departamento_list'
    ),
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name='Crear_Departamento'
    ),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'persona_app'


urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='Pagina_Inicio'
    ),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleado.as_view(),
        name='empleados_all'
    ),
    path(
        'listar-empleado-admin/',
        views.ListAllEmpleadoAdmin.as_view(),
        name='empleados_all_admin'
    ),
    path(
        'lista-by-area/<shortname>',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'buscar-empleado/',
        views.ListEmpleadosByKword.as_view()
    ),
    path(
        'listar-habilidades-empleado/',
        views.ListHabilidadesEmpleado.as_view()
    ),
    path(
        'ver-empleado/<pk>',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'ver-empleado-trabajo/',
        views.ListByTrabajoEmpleado.as_view()
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='actualizar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluiomos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.


class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de las Empresa'
        ordering = ['name']
        unique_together = ('name', 'shor_name')

    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name

applications/departamento/forms.py
from django import forms


class NewDepartamentoForm(forms.Form):
    """NewDepartamentoForm definition."""

    # TODO: Define form fields here
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic import(
    ListView
)
# Create your views here.
from applications.persona.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm


class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name = 'departamentos'


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = reverse_lazy('departamento_app:departamento_list')

    def form_valid(self, form):
        depa = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa

        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}
Lista departamentos
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Departamentos</h1>
        <div class="cell">
            <table>
                <tbody>


                    {% for departamentos in departamentos %}
                    <tr>
                        <td>{{ departamentos.name }}</td>
                        <td>{{ departamentos.shor_name }}</td>
                        <td><a class="button warning"
                                href="{% url 'persona_app:empleados_area' departamentos.shor_name  %}">Ver Empleados</a>
                        </td>
                    </tr>
                    {% endfor %}


                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
Registrar Departamento
{% endblock title %}

{% block content %}


{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST"> {% csrf_token %}

            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.nombre}}
                </label>
            </div>

            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.apellidos}}
                </label>
            </div>

            <div class="medium-6 cell">
                <label>Departamento:
                    {{form.departamento}}
            </div>

            <div class="medium-6 cell">
                <label>Nombre Corto:
                    {{form.shorname}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="success button">Guardar</button>
            </div>

        </form>
    </div>
</div>




{% endblock content %}